application:
  name: devzzz环境 @artifactId@
  version: dev环境 @version@
developer:
  name: devzz环境 xkcoding
  website: devzz环境 http://xkcoding.com
  qq: devzz环境 237497819
  phone-number: devzz环境 17326075631
