application:
  name: prod环境111 @artifactId@
  version: prod环境111 @version@
developer:
  name: prod环境11 xkcoding
  website: prod环境11 http://xkcoding.com
  qq: prod环境 237497819
  phone-number: prod环境 17326075631
