application:
  name: sit  环境 @artifactId@
  version: sit  环境 @version@
developer:
  name: sit  环境 xkcoding
  website: sit  环境 http://xkcoding.  com
  qq: sit  环境 2374  97819
  phone-number: sit  境 17326075  631
